### ISSUE TITLE
Request API key

### ISSUE THREAD

**Issue by jderekb** [microsoft/MSRC-Microsoft-Engage-API#3]
I am trying to get a API key for Abuse API.  Please advise as to how to obtain.  

The Engage API requires an API key. To obtain one, please log into the MSRC Portal and obtain the key from the Developer tab. Currently, generating an API key requires an @outlook.com, @live.com, or @microsoft.com email address.

**Comment by msrcgit** [comment]
To obtain an API key please visit:
https://portal.msrc.microsoft.com/en-us/developer

**Comment by mdressman** [comment]
Hello - there is a new API and it no longer requires an API Key - please see https://msrc.microsoft.com/report/developer for more info. Thank you!
