### ISSUE TITLE
Sample code uses incorrect time settings

### ISSUE THREAD

**Issue by robeving** [microsoft/MSRC-Microsoft-Engage-API#5]
https://github.com/microsoft/MSRC-Microsoft-Engage-API/blob/7a041f670888192527d4fd22ca96166df7209e54/src/msrcCars/CsharpExamples/C%23Code.cs#L40

This needs to be changed to DateTime.UtcNow.ToString("HH:mm:ss") otherwise provided timestamps are inconsistent and are not in 24hr format. Other code samples may be affected and should be checked.

**Comment by mdressman** [comment]
Hey @robeving, thank you for this. This API is being replaced with a new version with an updated data model. Documentation is available at https://msrc.microsoft.com/report/developer and there is more context at https://msrc-blog.microsoft.com/2021/02/01/new-and-improved-report-abuse-portal-and-api/
